- name: Install Docker on Ubuntu
  hosts: ubuntu_nodes
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64] https://download.docker.com/linux/ubuntu
          {{ ansible_lsb.codename }} stable
        state: present
        filename: docker

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: Ensure Docker server is started
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started